## from https://github.com/pestrada/android-tdd-playground/blob/master/.travis.yml
language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
sudo: false

android:
  components:
    - build-tools-19.1.0
    - extra
    - android-19
  licenses:
    - android-sdk-license-5be876d5

script: ./gradlew test
